# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89a7b78e0fecd2c57a42f17bdeb3e1150fe72d4135f20f3e27ac39439fe6b350ad078d82d924f05e5d8ff5351f11ada3508d64997cadc768b417038985200d7f

test:
  secret_key_base: cc186bdd715bdd524e8071e457deee511aaca57c41aed7ac221b98e1205fd8ef7b73452bf34573c68680480b5004bd7512da9cb0ef72cd6e7dd3fbf0a5e3f526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
